import { PrismaClient } from "@prisma/client"
const prisma = new PrismaClient();
const universities = [

"Université Internationale de Rabat - UIR",
"Université Mohammed VI des Sciences de Santé - UM6SS",
"Ecole Privée d'Ingénierie - ECINE",
"ISIAM Faculté des sciences de gestion - ISIAM",
"Ecole Polytechnique Privée d'Agadir - EPPA",
"Ecole Supérieure de Tourisme et de Technologie Hôtelière Privée - SupHôtellerie",
"Ecole Privée de Droit des Sciences Politiques et Humaines - EDSPH",
"Annexe Laâyoune d'ISIAM Faculté Privée des Sciences de Gestion - ISIAM Laâyoune",
"Annexe Laâyoune de l'Ecole Privée Polytechnique d'Agadir - EPPA Laâyoune",
"Faculté des Sciences de la Rééducation et des Techniques de Santé - FSRTS",
"Faculté privée de Management et de Gouvernance - FPMG",
"Ecole d'Ingénierie et d'Innovation Privée - E2IM",
"Ecole Supérieure d'Hôtellerie - SupHôtellerie",
"Ecole Supérieure d'Informatique Appliquée à la Gestion - ESIAG",
"Faculté privée de l'Art, Culture et Média - Audiovisuel - FPACM",
"Faculté privée des Métiers et Technologies de la Santé - FPMTS",
"Faculté Privée de Médecine de Marrakech - FPM Marrakech",
"Université Privée de Fès - UPF",
"Université Internationale d'Agadir - Universiapolis",
"Université Internationale de Casablanca - UIC",
"Ecole Supérieure d'Architecture de Casablanca - EAC",
"Ecole Centrale de Casablanca - ECC",
"ESCA Ecole de Management",
"Faculté Privée Mundiapolis de Management - Mundiapolis",
"Ecole d'Ingénierie Mundiapolis Privée - EIM",
"Institut Mundiapolis privé des Sciences Politiques Juridiques et Sociales - IMSPJ",
"Faculté Mundiapolis privée des Sciences de la Santé - FMSS",
"Faculté privée des Sciences de l'Ingénieur de Fès - FSI",
"Fès Business School - FBS",
"Ecole Supérieure Privée de Métiers d'Architecture d'Intérieur et de Bâtiment - ESMAB",
"Faculté des Sciences Paramédicales et Techniques de Santé de Fès - FSPTS",
"Africa Business School of OCP",
"School of Architecture, Planning et Design",
"Institute of Science, Technology and Innovation",
"Green Tech Institute",
"UM6P School of Computer Science - UM6P-CS",
"Institut Supérieur des Sciences Biologiques et Paramédicales - ISSBP",
"Faculty of Medical Sciences - FMS",
"Faculté Internationale de Médecine Dentaire de Rabat - FIMD",
"Ecole Supérieure des Sciences Paramédicales de Rabat - ESSPR",
"Faculté Internationale de Médecine de Rabat - FIMR",
"Ecole de Management Industriel - EMI",
"Faculté de Gouvernance, des Sciences Economiques et Sociales - FGSES",
"Ecole des Sciences de l'Agriculture, de la Fertilisation et de l'Environnement - ESAFE",
"Université Privée de Fès - UPF",
"Faculté des Sciences Infirmières et du Management Hospitalier - FASIMH",
"Institut Supérieur d'Ingénierie et des Technologies de Santé - ISITS",
"Ecole Supérieure de Génie Biomédical - ESG Bio",
"Ecole Internationale de Santé Publique - EISP",
"Faculté de Médecine - FM Rabat",
"Faculté des Sciences et des Techniques de Santé - FSTS",
"Ecole Supérieure de Génie Biomédical - ESG Bio",
"Ecole Supérieure d'Architecture de Rabat - ESAR",
"Faculté Internationale de Médecine Dentaire de Rabat - FIMD",
"Faculté des Sciences Infirmières et du Management Hospitalier - FASIMH",
"Ecole Supérieure de Tourisme et de Technologie Hôtelière - SupHôtellerie",
"Ecole Supérieure de Tourisme et de Technologie Hôtelière - SupHôtellerie",
"Faculté de Pharmacie Abulcasis - FPA",
"Ecole d'Ingénieurs Abulcasis - EIA",
"Faculté Euro-Méditerranéenne des Sciences Humaines et Sociales - FESH",
"Institut Euro-Méditerranéen des Technologies - INSA Euro-Med",
"Euromed Business School - EBS",
"Institut Euromed des Sciences Juridiques et Politiques - IESJP",
"Ecole Euro-Méditerranéenne d'Architecture, de Design et d'Urbanisme - EEMADU",
"Ecole Euro-Med d'Ingénierie Digitale et Intelligence Artificielle - EEIDIA",
"Ecole d'Ingénieur en Biomédical et Biotechnologie - EIBB",
"Euromed Polytechnic School - EPS",
"Faculté Euromed de Pharmacie - FEP",
"Faculté Euromed de Médecine - FEM",
"Université Internationale de Rabat - UIR",
"UIR Business School - UIR BS",
"UIR School of Aerospace Engineering - UIR SAE",
"UIR Institut des Etudes Politiques et Juridiques Sciences Po Rabat Privé - UIR IEPJ",
"Ecole Supérieure Privée d'Ingénierie de l'Energie - ECINE",
"Ecole Supérieure d'Architecture de Rabat - ESAR",
"Faculté Internationale de Médecine Dentaire de Rabat - FIMD",
"Ecole Supérieure des Sciences Paramédicales de Rabat - ESSPR",
"Faculté Internationale de Médecine de Rabat - FIMR",
"Groupe Institut supérieur de commerce et d'administration des entreprises (ISCAE)",
"Institut Supérieur du Tourisme de Tanger (ISIT)",
"Ecole des sciences de l'information (ESI)",
"Institut Supérieur de l'information et de la communication (ISIC)",
"Institut national des postes et télécommunications (INPT)",
"Ecole nationale d'agriculture de Meknès (ENAM)",
"Ecole nationale forestière d'ingénieurs (ENFI)",
"Institut supérieur des études maritimes (ISEM)",
"Institut agronomique et vétérinaire Hassan II (IAV)",
"Institut national de statistique et d'économie appliquée (INSEA)",
"Ecole nationale supérieur des mines de Rabat (ENSMR)",
"Ecole Hassania des travaux publics (EHTP)",
"Ecole supérieure de l'industrie du textile et de l'Habillement (ESITH)",
"Académie internationale Mohamed VI de l'Aviation civile (AIAC)",
"Institut royal de formation des cadres de la jeunesse et des sports (IRFCJS)",
"Institut des sciences de l'archéologie et du patrimoine (INSAP)",
"Institut supérieur d'art dramatique et d'animation culturelle (ISADAC)",
"Institut supérieur des métiers de l'audio-visuel et du cinema (ISMAC)",
"Institut national des beaux arts (INBA)",
"Ecole nationale d'architecture - Rabat (ENA)",
"Ecole nationale d'architecture - Marrakech (ENA)",
"Ecole nationale d'architecture - Tétouan (ENA)",
"Ecole nationale d'architecture - Fès (ENA)",
"Ecole nationale d'architecture - Agadir(ENA)",
"Ecole nationale d'architecture - Oujda(ENA)",
"Institut national d'aménagement et d'urbanisme (INAU)",
"Centre régional des métiers de l'éducation et de la formation - Rabat-Salé-Kénitra (CRMEF)",
"Centre régional des métiers de l'éducation et de la formation - Casablanca-Settat (CRMEF)",
"Centre régional des métiers de l'éducation et de la formation - Merrakech-Safi (CRMEF)",
"Centre régional des métiers de l'éducation et de la formation - Fès-Meknes (CRMEF)",
"Centre régional des métiers de l'éducation et de la formation - Tanger-Tétouan-Houceima (CRMEF)",
"Centre régional des métiers de l'éducation et de la formation - Région de l'oriental (CRMEF)",
"Centre régional des métiers de l'éducation et de la formation - Deraa-Tafilalte (CRMEF)",
"Centre régional des métiers de l'éducation et de la formation - Souss-Massa (CRMEF)",
"Centre régional des métiers de l'éducation et de la formation - Béni mellal-Khénifra (CRMEF)",
"Centre régional des métiers de l'éducation et de la formation - Laayoune-Saquia El hamra (CRMEF)",
"Centre régional des métiers de l'éducation et de la formation - Guelmime-Oued Noun (CRMEF)",
"Centre régional des métiers de l'éducation et de la formation - Dakhla-Oued Eddahab (CRMEF)",
"Centre d'orientation et de planification de l'éducation (COPE)",
"Centre de formation des inspecteurs de l'enseignement (CFIE)",
"Institut national de l'action sociale (INAS)",
"Ecole Nationale de santé publique (ENSP)",
"Institut supérieur des professions infirmières et technique de santé - Rabat (ISPITS)",
"Institut supérieur des professions infirmières et technique de santé - Casablanca (ISPITS)",
"Institut supérieur des professions infirmières et technique de santé - Marrakech (ISPITS)",
"Institut supérieur des professions infirmières et technique de santé - Fès (ISPITS)",
"Institut supérieur des professions infirmières et technique de santé - Tétouan (ISPITS)",
"Institut supérieur des professions infirmières et technique de santé - Oujda (ISPITS)",
"Institut supérieur des professions infirmières et technique de santé - Agadir (ISPITS)",
"Institut supérieur des professions infirmières et technique de santé - Béni Mellal (ISPITS)",
"Institut supérieur des professions infirmières et technique de santé - Errachidia (ISPITS)",
"Institut supérieur des professions infirmières et technique de santé - Laayoune (ISPITS)",
"Université Internationale de Rabat- UIR",
"Université Mohammed VI des Sciences de Santé - UM6SS - Casablanca",
"Université Internationale Abulcasis des Sciences de Santé- UIASS - Rabat",
"Université Euro-méditerranéenne de Fès - UEMF",
"Université Mohammed VI Polytechnique - UM6P- Ben Guérir",
"Université Privée Marrakech Tensift El Haouz - UPM",
"Université Internationale d'Agadir - Universiapolis",
"Université Internationale de Casablanca - UIC",
"Ecole Supérieure d'Architecture de Casablanca - EAC",
"Ecole Centrale de Casablanca - ECC",
"ESCA Ecole de Management",
"Université Privée Mundiapolis- Casablanca",
"Université Privée de Fès - UPF",
"Sup de Co - Ecole Supérieure de Commerce - Marrakech",
"Ecole Supérieure en Ingénierie de l'Information, Télécoms, Management et Génie Civil - ESTEM- Casablanca",
"Institut Supérieur du Génie Appliqué Casablanca - IGA Casablanca",
"Ecole Marocaine des Sciences de l'Ingénieur Casablanca - EMSI-Casablanca",
"Ecole Marocaine des Sciences de l'Ingénieur Rabat- EMSI-Rabat",
"Ecole Marocaine des Sciences de l'Ingénieur Marrakech- EMSI-Marrakech",
"Institut Supérieur d'Ingénierie et des Affaires Privé - Rabat - ISGA-Rabat",
"Institut Supérieur d'Ingénierie et des Affaires - ISGA-Fès",
"Institut Supérieur d'Ingénierie et des Affaires - ISGA-Marrakech",
"Ecole Marocaine d'Ingénierie - EMG-Rabat",
"Institut Supérieur de transport et de la Logistique - ISTL-Casablanca",
"Institut des Hautes Etudes de Management- HEM Casablanca",
"Ecole des Hautes Etudes Economiques, Commerciales et d'Ingénierie - HEEC - Marrakech",
"Ecole Supérieure de Management de Commerce et d'Informatique- SUP'MANAGEMENT- Fès",
"International Institute for Higher Education in Morocco - IIHEM - Rabat",
"Ecole d'Ingénierie en Génie des Systèmes Industriels de Casablanca- EIGSICA",
"Ecole Supérieure de Management, Informatique et Télécommunication- SUPMTI Rabat",
"Ecole des Hautes Etudes d'Ingénierie- EHEIO- Oujda",
"Ecole de Management et d'Administration des Affaires- Agadir",
"Institut Supérieur d'Ingénierie et des Affaires - ISGA-Casablanca",
"Institut Supérieur de Management d'administration et de Genie Informatique -ISMAGI",
"Ecoles des Hautes Etudes en Sciences et Techniques de l'Ingénierie et du Management Privée - HESTIM",
"Ecole des Hautes Etudes Commerciales et Informatiques - Casablanca (HECI-Casablanca)",
"Ecole Supérieure des Sciences Economiques et de Management - ESSEM",
"Ecole Supérieure de Management et de Gestion des Ressources Humaines - SU'RH",
"Ecole Supérieure des Sciences de Santé - ESSS- Casablanca",
"Ecole des Nouvelles Sciences et Ingénierie - ENSIT - Tanger",
"Ecoles Marocaines des Science de l'Ingénieur en Informatique Industrielle et informatique de gestion - EMSI - Tanger",
"Ecole privée des Hautes Etudes Comptables et Financières - HECF Fès",
"Institut Supérieur du Génie Appliqué IGA Casablanca",
"Ecole Supérieure Internationale de Gestion ESIG Casablanca",
"Ecole des Hautes Etudes Commerciales et Informatiques HECI Casablanca",
"Ecole Marocaine des Sciences de l'Ingénieur en Informatique de Gestion et en Informatique Industrielle",
"Sup de co Ecole Supérieure de Commerce Marrakech",
"High Technology School in Morocco HIGH-TECH Rabat",
"International Institute for Higher Education in Morocco IIHEM Rabat",
"Institut des Hautes Etudes de Management HEM Casablanca",
"Institut Supérieur de Gestion et de Commerce ISGC Casablanca",
"Ecole des Hautes Etudes Commerciales et Informatiques HECI Rabat",
"ESCA Ecole de Managment Casablanca",
"Ecole des Hautes Etudes Commerciales et Informatiques HECI Meknès",
"Ecole des Hautes Etudes Commerciales et Informatiques HECI Fès",
"Ecole Polyvalente Supérieure d'Informatique et d'Electronique et de Management",
"Ecole des Hautes Etudes de Commerce HEC Rabat",
"Institut des Hautes Etudes de Management HEM Rabat",
"Institut Supérieur de Formation en Technologie Alimentaire et Biopharmaceutique",
"Ecole Supérieure de Management, du Commerce et d'Informatique Sup-Management Fès",
"Institut des Hautes Etudes Bancaires, Financières et Managériales HBFG Casablanca",
"Ecole Supérieure d'Optique et de Lunetterie ESOL Fès",
"Institut Supérieur d'Ingénierie et des Affaires Privé-Rabat ISGA-Rabat Rabat",
"Ecole des Hautes Etudes de Biotechnologie et de Santé Privée EHEB Casablanca",
"Ecole Supérieure des Réseaux Informatiques et de Management ESRIM Settat",
"Institute for Leadership and communication Studies ILCS Rabat",
"Ecole des Hautes Etudes Commerciales et Informatiques HECI Kénitra",
"Ecole Supérieure de Communication et de Publicité Com'Sup Casablanca",
"Ecole des Hautes Etudes Economiques, Commerciales et d'Ingénierie HEEC Marrakech",
"Moroccan Computer Sciences And Management Business School",
"Institut des Hautes Etudes Bancaires, Financières et Managériales HBFG Oujda",
"Ecole Marocaine de Banque et de Commerce International EMBCI Rabat",
"Ecole Supérieure d'Optique Appliquée et du Paramédicale privé ESO Rabat",
"Institut Supérieur Maghrébin d'Optique et d'Optométrie ISMOO Casablanca",
"Ecole Supérieure d'Architecture d'Intérieur ESAI Rabat",
"Ecole Supérieure d'Ingénierie en Sciences Appliquées ESISA Fès",
"Ecole Supérieure de Kinésithérapie et du Paramedical_ESKP ESKP Casablanca",
"Ecole des Hautes études de l'Ingénierie Commerciale et Management",
"Haute Ecole de Kinésithérapie HEK Casablanca",
"Ecole Supérieure en Ingénierie d'Information, Télécommunication, Management et Génie Civil",
"Ecole Supérieure des Sciences Techniques et de Management SUPTEM Tanger",
"Institut Polytechnique Privé de Casablanca Casablanca",
"Institut Supérieur du Journalisme et de Communication ISJC Casablanca",
"Ecole des Hautes Etudes Commerciales et Informatiques HECI Oujda",
"Institut Supérieur des sciences de Technologie SIST Casablanca",
"Institut Supérieur Vinci d'Ingénierie Informatique et de Réseaux de Télécommunications",
"Institut Supérieur du Journalisme et de l'Information IFJSUP Casablanca",
"Institut des Hautes Etudes de Management HEM Marrakech",
"Ecole Supérieure de Psychologie ESP Casablanca",
"Ecole des Hautes Etudes comptables et Financières HECF Fès",
"Ecole Supérieure des Multimédia, Informatique et Réseaux SUPEMIR Casablanca",
"Ecole des Hautes Etudes comptables et Financières HECF Fès",
"Ecole Supérieure des Multimédia, Informatique et Réseaux SUPEMIR Casablanca",
"Ecole Supérieure des Etudes Juridiques et Economiques ESEJE Mohammadia",
"Ecole Marocaine des Sciences de l'Ingénieur en Informatique de Gestion et en Informatique Industrielle EMSI Marrakech",
"Institut Supérieur d'Optique Théorique et Appliquée Privé ISOTA Casablanca",
"Ecole Supérieure de Design Art Com-Sup Casablanca",
"Ecole des Hautes Etudes Poly Management HEP Management Oujda",
"Institut Supérieur d'Ingénierie et des Affaires Privé-Marrakech ISGA-Marrakech Marrakech",
"Ecole Supérieure de Telécommunication et de Management SUPTEMA Fès",
"Ecole Supérieure d'Architecture de Casablanca EAC Casablanca",
"Private International Institut of Management And Technologie PIIMT Rabat",
"Ecole Supérieure des Hautes Etudes en Technologie de l'Information et de la Communication Privée Sup Technology Casablanca",
"Institut Supérieur du Transport et de la Logistique ISTL Casablanca",
"Institut Spécialié Privé des Sciences de la Santé ISPS Casablanca",
"Ecole Supérieure de Management et de Communication ESMC Casablanca",
"Ecole Supérieure de Design Art com sup Rabat",
"Ecole Supérieure de Design et des Arts Visuels ESDAV Casablanca",
"Ecole Supérieure de Management, Informatique et Télécommunications SUPMTI Rabat",
"Ecole d'Ingénierie en Génie des Systèmes Industriels de Casablanca EIGSICA Casablanca",
"Institut des Hautes Etudes en Paramédical du Sud IHEPS Marrakech",
"Ecoles des Hautes Etudes des Sciences et Techniques de l'Ingénierie et du Management Privée HESTIM Casablanca",
"Ecole Supérieure de Commerce et de Gestion des Affaires Privée ESCGA Tanger",
"Ecole Supérieure Privée des Hautes Etudes Managériales de Tanger HEMT Tanger",
"Ecole de Management et d'Administration des Affaires Agadir",
"Ecole des Métiers, de Commerce, de Gestion et d'Informatique Privée EMCGI Tanger",
"Institut Supérieur des Hautes Etudes en Développement Durable ISHEDD Rabat",
"Ecole Supérieure Privée de l'lnnovation lnformatique et Technologique INNOV INFO Casablanca",
"Ecole Supérieure de Management et de Gestion des Ressources Humaines SUP'RH Casablanca",
"Ecole Supérieure du Management des Entreprises du Détroit MEDSUP Management Tanger",
"Ecole Supérieure des Arts Visuels Privée ESAV Marrakech",
"Ecole Supérieure de Journalisme et de Communication ESJC Casablanca",
"Institut Supérieur des Etudes de la Santé Privé Mohammedia ISESMO Mohammadia",
"Institut Supérieur Privé de Génie Informatique SUP ISI Tétouan",
"Ecole des Hautes Etudes Comptables et Financières HECF Meknès",
"Ecole Marocaine d'Ingénierie EMG Rabat",
"Institut Supérieur de Comptabilité, d'Administration et de Commerce ICACSUP Kénitra",
"Ecole des Nouvelles Sciences et Ingénierie ENSIT Tanger",
"Ecole Supérieure de Management Informatique et Télécommunications Privée d'Oujda SUPMTI Oujda",
"Hautes Etudes de Commerce, de Gestion et d'Informatique HECGI Kénitra",
"Ecole Supérieure de Management et d'Ingénierie de l'Orient Orient Sup de Management Taza",
"Institut Supérieur d'Ingénierie et des Affaires Privé-Fès ISGA-Fès Fès",
"Superior Institutions Of Sciences And Technology SIST Rabat",
"Ecole Supérieure d'Ingénierie Automobile et Aéronautique ESI2A Fès",
"Institut Supérieur de Management, d'Administration et de Génie Informatique ISMAGI Rabat",
"Ecole Supérieure de de l'Aeronautique et la Haute Technologie AEROSUP Casablanca",
"Ecole Supérieure de Finance et d'Audit FINAN SUP Tanger",
"Ecole Supérieure des Sciences Economiques et de Management ESSEM Casablanca",
"Ecole Supérieure des Sciences de la Santé ESSS Casablanca",
"Ecole Supérieure des Sciences Commerciales et de Gestion ESSCG Tanger",
"Ecole Supérieure de Management, Informatique et Télécommunication SUPMTI Meknès",
"Ecole Centrale de Casablanca ECC Casablanca",
"Institut Supérieur du Journalisme et de l'Information IFJSUP Marrakech",
"ADALIA Private Institute of Management ADALIA Casablanca",
"Ecole Supérieure Business de Berrechid Privée BERRECHID",
"Ecole des Sciences Economiques et Commerciales ESSEC Salé (Commune Bouknadel)",
"YNCREA Maroc Ecole d'Ingénierie Privée Rabat",
"EMLC business school EMLC Casablanca",
"Institut Supérieur Privé des Sciences de l'Ingénieur Technologia Privée Rabat",
"Ecole Marocaine des Sciences de l'Ingénieur en Informatique de Gestion et en Informatique Industrielle EMSI Tanger",
"Institut Privé des Hautes Etudes Marocaines d'Ingénierie HEM Engineering School Casablanca",
"Ecole Supérieure des Affaires de Casablanca ESAC Casablanca",
"Institut Supérieur des Etudes Paramédicales de Casablanca ISEP Casablanca",
"Institut des Hautes Etudes Paramédicales Souss IHEPS Agadir",
"lnstitut Supérieur Privé des Etudes Paramédicales ISPEP Casablanca",
"Ecole Privée Supérieure d'Ingénierie Numérique et Systèmes d'Intelligence Artificielle EPSINSIA Casablanca",
"International Institute of Management Casablanca privé IIMC Bouskoura",
"International Institute of Engineering Casablanca privé IIEC Bouskoura",
"Université Mohamed V - Rabat",
"Université Hassan II - Casablanca",
"Université Sidi Mohammed Ben Abdellah - Fès",
"Université Mohammed Premier - Oujda",
"Université Cadi Ayyad - Marrakech",
"Université Moulay Smail - Meknès",
"Université Abdelmalek Essaadi - Tétouan",
"Université Chouaib Doukkali - El jadida",
"Université Ibn Tofail - Kénitra",
"Université Ibn Zohr - Agadir",
"Université Hassan Premier - Settat",
"Université Sultan Moulay Slimane - Béni Mellal",
]
export const seedUniversities = async () => {
    await prisma.ecole.deleteMany().catch(err => {
        throw err;
    });
    await prisma.ecole
        .createMany({
            data: universities.map(university => ({
                nom: university,
            })),
        })
        .catch(err => {
            throw err;
        });

}

