import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const seedPays = async () => {
const pays = [
    { code: 'AF', nom: "L'Afghanistan" },
    { code: 'AX', nom: 'Iles Aland' },
    { code: 'AL', nom: 'Albanie' },
    { code: 'DZ', nom: 'Algérie' },
    { code: 'AS', nom: 'Samoa américaines' },
    { code: 'AD', nom: 'Andorre' },
    { code: 'AO', nom: "L'Angola" },
    { code: 'AI', nom: 'Anguilla' },
    { code: 'AQ', nom: 'Antarctique' },
    { code: 'AG', nom: 'Antigua-et-Barbuda' },
    { code: 'AR', nom: 'Argentine' },
    { code: 'AM', nom: 'Arménie' },
    { code: 'AW', nom: 'Aruba' },
    { code: 'AU', nom: 'Australie' },
    { code: 'AT', nom: "L'Autriche" },
    { code: 'AZ', nom: 'Azerbaïdjan' },
    { code: 'BS', nom: 'Bahamas' },
    { code: 'BH', nom: 'Bahreïn' },
    { code: 'BD', nom: 'Bangladesh' },
    { code: 'BB', nom: 'Barbade' },
    { code: 'BY', nom: 'Biélorussie' },
    { code: 'BE', nom: 'Belgique' },
    { code: 'BZ', nom: 'Belize' },
    { code: 'BJ', nom: 'Bénin' },
    { code: 'BM', nom: 'Bermudes' },
    { code: 'BT', nom: 'Bhoutan' },
    { code: 'BO', nom: 'Bolivie' },
    { code: 'BQ', nom: 'Bonaire, Saint-Eustache et Saba' },
    { code: 'BA', nom: 'Bosnie Herzégovine' },
    { code: 'BW', nom: 'Botswana' },
    { code: 'BV', nom: 'Île Bouvet' },
    { code: 'BR', nom: 'Brésil' },
    { code: 'IO', nom: "Territoire britannique de l'océan Indien" },
    { code: 'BN', nom: 'Brunei Darussalam' },
    { code: 'BG', nom: 'Bulgarie' },
    { code: 'BF', nom: 'Burkina Faso' },
    { code: 'BI', nom: 'Burundi' },
    { code: 'KH', nom: 'Cambodge' },
    { code: 'CM', nom: 'Cameroun' },
    { code: 'CA', nom: 'Canada' },
    { code: 'CV', nom: 'Cap-Vert' },
    { code: 'KY', nom: 'Îles Caïmans' },
    { code: 'CF', nom: 'République centrafricaine' },
    { code: 'TD', nom: 'Tchad' },
    { code: 'CL', nom: 'Chili' },
    { code: 'CN', nom: 'Chine' },
    { code: 'CX', nom: "L'île de noël" },
    { code: 'CC', nom: 'Îles Cocos (Keeling}' },
    { code: 'CO', nom: 'Colombie' },
    { code: 'KM', nom: 'Comores' },
    { code: 'CG', nom: 'Congo' },
    { code: 'CD', nom: 'Congo, République démocratique du Congo' },
    { code: 'CK', nom: 'les Îles Cook' },
    { code: 'CR', nom: 'Costa Rica' },
    { code: 'CI', nom: "Côte d'Ivoire" },
    { code: 'HR', nom: 'Croatie' },
    { code: 'CU', nom: 'Cuba' },
    { code: 'CW', nom: 'Curacao' },
    { code: 'CY', nom: 'Chypre' },
    { code: 'CZ', nom: 'République Tchèque' },
    { code: 'DK', nom: 'Danemark' },
    { code: 'DJ', nom: 'Djibouti' },
    { code: 'DM', nom: 'Dominique' },
    { code: 'DO', nom: 'République dominicaine' },
    { code: 'EC', nom: 'Equateur' },
    { code: 'EG', nom: 'Egypte' },
    { code: 'SV', nom: 'Le Salvador' },
    { code: 'GQ', nom: 'Guinée Équatoriale' },
    { code: 'ER', nom: 'Érythrée' },
    { code: 'EE', nom: 'Estonie' },
    { code: 'ET', nom: 'Ethiopie' },
    { code: 'FK', nom: 'Îles Falkland (Malvinas}' },
    { code: 'FO', nom: 'Îles Féroé' },
    { code: 'FJ', nom: 'Fidji' },
    { code: 'FI', nom: 'Finlande' },
    { code: 'FR', nom: 'France' },
    { code: 'GF', nom: 'Guyane Française' },
    { code: 'PF', nom: 'Polynésie française' },
    { code: 'TF', nom: 'Terres australes françaises' },
    { code: 'GA', nom: 'Gabon' },
    { code: 'GM', nom: 'Gambie' },
    { code: 'GE', nom: 'Géorgie' },
    { code: 'DE', nom: 'Allemagne' },
    { code: 'GH', nom: 'Ghana' },
    { code: 'GI', nom: 'Gibraltar' },
    { code: 'GR', nom: 'Grèce' },
    { code: 'GL', nom: 'Groenland' },
    { code: 'GD', nom: 'Grenade' },
    { code: 'GP', nom: 'Guadeloupe' },
    { code: 'GU', nom: 'Guam' },
    { code: 'GT', nom: 'Guatemala' },
    { code: 'GG', nom: 'Guernesey' },
    { code: 'GN', nom: 'Guinée' },
    { code: 'GW', nom: 'Guinée-Bissau' },
    { code: 'GY', nom: 'Guyane' },
    { code: 'HT', nom: 'Haïti' },
    { code: 'HM', nom: 'Îles Heard et McDonald' },
    { code: 'VA', nom: 'Saint-Siège (État de la Cité du Vatican}' },
    { code: 'HN', nom: 'Honduras' },
    { code: 'HK', nom: 'Hong Kong' },
    { code: 'HU', nom: 'Hongrie' },
    { code: 'IS', nom: 'Islande' },
    { code: 'IN', nom: 'Inde' },
    { code: 'ID', nom: 'Indonésie' },
    { code: 'IR', nom: 'Iran (République islamique d' },
    { code: 'IQ', nom: 'Irak' },
    { code: 'IE', nom: 'Irlande' },
    { code: 'IM', nom: 'île de Man' },
    { code: 'IL', nom: 'Israël' },
    { code: 'IT', nom: 'Italie' },
    { code: 'JM', nom: 'Jamaïque' },
    { code: 'JP', nom: 'Japon' },
    { code: 'JE', nom: 'Jersey' },
    { code: 'JO', nom: 'Jordan' },
    { code: 'KZ', nom: 'Kazakhstan' },
    { code: 'KE', nom: 'Kenya' },
    { code: 'KI', nom: 'Kiribati' },
    { code: 'KP', nom: 'République populaire démocratique de Corée' },
    { code: 'KR', nom: 'Corée, République de' },
    { code: 'XK', nom: 'Kosovo' },
    { code: 'KW', nom: 'Koweit' },
    { code: 'KG', nom: 'Kirghizistan' },
    { code: 'LA', nom: 'République démocratique populaire lao' },
    { code: 'LV', nom: 'Lettonie' },
    { code: 'LB', nom: 'Liban' },
    { code: 'LS', nom: 'Lesotho' },
    { code: 'LR', nom: 'Libéria' },
    { code: 'LY', nom: 'Jamahiriya arabe libyenne' },
    { code: 'LI', nom: 'Liechtenstein' },
    { code: 'LT', nom: 'Lituanie' },
    { code: 'LU', nom: 'Luxembourg' },
    { code: 'MO', nom: 'Macao' },
    {
        code: 'MK',
        nom: 'Macédoine, ancienne République yougoslave de',
    },
    {code: 'MG', nom: 'Madagascar' },
    {code: 'MW', nom: 'Malawi' },
    {code: 'MY', nom: 'Malaisie' },
    {code: 'MV', nom: 'Maldives' },
    {code: 'ML', nom: 'Mali' },
    {code: 'MT', nom: 'Malte' },
    {code: 'MH', nom: 'Iles Marshall' },
    {code: 'MQ', nom: 'Martinique' },
    {code: 'MR', nom: 'Mauritanie' },
    {code: 'MU', nom: 'Ile Maurice' },
    {code: 'YT', nom: 'Mayotte' },
    {code: 'MX', nom: 'Mexique' },
    {code: 'FM', nom: 'Micronésie, États fédérés de' },
    {code: 'MD', nom: 'Moldova, République de' },
    {code: 'MC', nom: 'Monaco' },
    {code: 'MN', nom: 'Mongolie' },
    {code: 'ME', nom: 'Monténégro' },
    {code: 'MS', nom: 'Montserrat' },
    {code: 'MA', nom: 'Maroc' },
    {code: 'MZ', nom: 'Mozambique' },
    {code: 'MM', nom: 'Myanmar' },
    {code: 'NA', nom: 'Namibie' },
    {code: 'NR', nom: 'Nauru' },
    {code: 'NP', nom: 'Népal' },
    {code: 'NL', nom: 'Pays-Bas' },
    {code: 'AN', nom: 'Antilles néerlandaises' },
    {code: 'NC', nom: 'Nouvelle Calédonie' },
    {code: 'NZ', nom: 'Nouvelle-Zélande' },
    {code: 'NI', nom: 'Nicaragua' },
    {code: 'NE', nom: 'Niger' },
    {code: 'NG', nom: 'Nigeria' },
    {code: 'NU', nom: 'Niue' },
    {code: 'NF', nom: "l'ile de Norfolk" },
    {code: 'MP', nom: 'Îles Mariannes du Nord' },
    {code: 'NO', nom: 'Norvège' },
    {code: 'OM', nom: 'Oman' },
    {code: 'PK', nom: 'Pakistan' },
    {code: 'PW', nom: 'Palau' },
    {code: 'PS', nom: 'Territoire palestinien, occupé' },
    {code: 'PA', nom: 'Panama' },
    {code: 'PG', nom: 'Papouasie Nouvelle Guinée' },
    {code: 'PY', nom: 'Paraguay' },
    {code: 'PE', nom: 'Pérou' },
    {code: 'PH', nom: 'Philippines' },
    {code: 'PN', nom: 'Pitcairn' },
    {code: 'PL', nom: 'Pologne' },
    {code: 'PT', nom: 'Le Portugal' },
    {code: 'PR', nom: 'Porto Rico' },
    {code: 'QA', nom: 'Qatar' },
    {code: 'RE', nom: 'Réunion' },
    {code: 'RO', nom: 'Roumanie' },
    {code: 'RU', nom: 'Fédération Russe' },
    {code: 'RW', nom: 'Rwanda' },
    {code: 'BL', nom: 'Saint Barthélemy' },
    {code: 'SH', nom: 'Sainte-Hélène' },
    {code: 'KN', nom: 'Saint-Christophe-et-Niévès' },
    {code: 'LC', nom: 'Sainte-Lucie' },
    {code: 'MF', nom: 'Saint Martin' },
    {code: 'PM', nom: 'Saint-Pierre-et-Miquelon' },
    {code: 'VC', nom: 'Saint-Vincent-et-les-Grenadines' },
    {code: 'WS', nom: 'Samoa' },
    {code: 'SM', nom: 'Saint Marin' },
    {code: 'ST', nom: 'Sao Tomé et Principe' },
    {code: 'SA', nom: 'Arabie Saoudite' },
    {code: 'SN', nom: 'Sénégal' },
    {code: 'RS', nom: 'Serbie' },
    {code: 'CS', nom: 'Serbie et Monténégro' },
    {code: 'SC', nom: 'les Seychelles' },
    {code: 'SL', nom: 'Sierra Leone' },
    {code: 'SG', nom: 'Singapour' },
    {code: 'SX', nom: 'St Martin' },
    {code: 'SK', nom: 'Slovaquie' },
    {code: 'SI', nom: 'Slovénie' },
    {code: 'SB', nom: 'Les îles Salomon' },
    {code: 'SO', nom: 'Somalie' },
    {code: 'ZA', nom: 'Afrique du Sud' },
    {code: 'GS', nom: 'Géorgie du Sud et îles Sandwich du Sud' },
    {code: 'SS', nom: 'Soudan du sud' },
    {code: 'ES', nom: 'Espagne' },
    {code: 'LK', nom: 'Sri Lanka' },
    {code: 'SD', nom: 'Soudan' },
    {code: 'SR', nom: 'Suriname' },
    {code: 'SJ', nom: 'Svalbard et Jan Mayen' },
    {code: 'SZ', nom: 'Swaziland' },
    {code: 'SE', nom: 'Suède' },
    {code: 'CH', nom: 'la Suisse' },
    {code: 'SY', nom: 'République arabe syrienne' },
    {code: 'TW', nom: 'Taiwan, Province de Chine' },
    {code: 'TJ', nom: 'Tadjikistan' },
    {code: 'TZ', nom: 'Tanzanie, République-Unie de' },
    {code: 'TH', nom: 'Thaïlande' },
    {code: 'TL', nom: 'Timor-Leste' },
    {code: 'TG', nom: 'Aller' },
    {code: 'TK', nom: 'Tokelau' },
    {code: 'TO', nom: 'Tonga' },
    {code: 'TT', nom: 'Trinité-et-Tobago' },
    {code: 'TN', nom: 'Tunisie' },
    {code: 'TR', nom: 'Turquie' },
    {code: 'TM', nom: 'Turkménistan' },
    {code: 'TC', nom: 'îles Turques-et-Caïques' },
    {code: 'TV', nom: 'Tuvalu' },
    {code: 'UG', nom: 'Ouganda' },
    {code: 'UA', nom: 'Ukraine' },
    {code: 'AE', nom: 'Emirats Arabes Unis' },
    {code: 'GB', nom: 'Royaume-Uni' },
    {code: 'US', nom: 'États-Unis' },
    {code: 'UM', nom: 'Îles mineures éloignées des États-Unis' },
    {code: 'UY', nom: 'Uruguay' },
    {code: 'UZ', nom: 'Ouzbékistan' },
    {code: 'VU', nom: 'Vanuatu' },
    {code: 'VE', nom: 'Venezuela' },
    {code: 'VN', nom: 'Viet Nam' },
    {code: 'VG', nom: 'Îles Vierges britanniques' },
    {code: 'VI', nom: 'Îles Vierges américaines, États-Unis' },
    {code: 'WF', nom: 'Wallis et Futuna' },
    {code: 'YE', nom: 'Yémen' },
    {code: 'ZM', nom: 'Zambie' },
    {code: 'ZW', nom: 'Zimbabwe' },
];

await prisma.pays.deleteMany().catch(err => {
    throw err;
});
await prisma.pays
    .createMany({
        data: pays.map(p => ({
            code: p.code,
            nom: p.nom,
        })),
    })
    .catch(err => {
        throw err;
    });

}

export default seedPays; 